### PR TITLE
[NIFI-10325] force UTC timezone expected by date format

### PR DESCRIPTION
**Pull request by hboutemy**
see https://issues.apache.org/jira/browse/NIFI-10325

this is a complement to #16

### CODE REVIEW

**Comment by hboutemy** [comment]
@kevdoran please review

**Comment by kevdoran** [comment]
Thanks for the bump @hboutemy. Will review

**Comment by hboutemy** [comment]
@kevdoran please
many non-reproducible bits of NiFi 1.19.0 are because of this issue...

**Review by kevdoran — APPROVED** [review]
Thanks @hboutemy. +1, merging. I'll make sure we do a release of this plugin so the next NiFi release includes this improvement.

**Pull request merged**
